cache:
- node_modules

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

clone_depth: 1

platform:
  - x64

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # Let's try to get things working
  # Install Node 8 ---------------------------------------------------------
  - ps: Install-Product node 8 x64
  # Typical npm stuff ------------------------------------------------------
  - npm version
  # Installation, deps -----------------------------------------------------
  - npm install --no-optional --no-color --no-progress

# We don't actually run the full test suite (that's a TODO left, but we do
# attempt to build).
test_script:
  - npm run test

# Set build version format here instead of in the admin panel.
build: off
version: "{build}"